module.exports = {
    SET_PERSONS: 'SET_PERSONS',
    SET_FRIENDS: 'SET_FRIENDS',
    SET_EVENTS: 'SET_EVENTS',
    SET_ANNOUNCEMENTS: 'SET_ANNOUNCEMENTS',
    SET_OBJECT: 'SET_OBJECT',
    CLOSE: 'CLOSE',
    OPEN: 'OPEN',
    SUBMIT_CONTACT_FORM: 'SUBMIT_CONTACT_FORM',
    GET_NEW_LIST: 'GET_NEW_LIST',
}